server:
  port: 8080

app:
  security:
    public-routes:
      - "/api/v1/account/auth/login"
      - "/api/v1/account/auth/signup"
      - "/api/v1/account/webhooks/**"
      - "/api/v1/workspace/public/**"

spring:
  cloud:
    gateway.server.webflux:
      routes:
        # Account Service (context-path: /account)
        - id: account-service
          uri: ${ACCOUNT_SERVICE_URI:lb://account-service}
          predicates:
            - Path=/api/v1/account/**
          filters:
            - StripPrefix=2
            
         # Workspace Service (context-path: /workspace)
        - id: workspace-service
          uri: ${WORKSPACE_SERVICE_URI:lb://workspace-service}
          predicates:
            - Path=/api/v1/workspace/**
          filters:
            - StripPrefix=2

        # Intelligence Service  (context-path: /intelligence)
        - id: intelligence-service
          uri: ${INTELLIGENCE_SERVICE_URI:lb://intelligence-service}
          predicates:
            - Path=/api/v1/intelligence/**
          filters:
            - StripPrefix=2
