server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable-intelligence-db
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver
    
  ai:
    openai:
      timeout: 180s
      api-key: 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
      # base-url: https://openrouter.ai/api
      # base-url: https://openrouter.ai/api/v1
      base-url: base-url: https://openrouter.ai/api/v1
      chat:
        options:
          model: nvidia/nemotron-3-ultra-550b-a55b:free
          temperature: 0.0
