server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable-intelligence-db
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
  openai:
   
    base-url: https://openrouter.ai/api/v1
    chat:
      options:
        model: nvidia/nemotron-3-ultra-550b-a55b:free
        temperature: 0.0 
