server:
  port: 9020
  servlet.context-path: /workspace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable-workspace-db
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  project-bucket: projects


---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.lovable-core.svc.cluster.local:5432/workspace_db
    username: workspace_user
    password: ${DB_PASSWORD}
  data:
    redis:
      host: redis.lovable-core.svc.cluster.local
      port: 6379

minio:
  url: http://minio.lovable-core.svc.cluster.local:9000
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  project-bucket: projects
